#!/usr/bin/env node

var serverFactory = require('spa-server')

var server = serverFactory.create({
  path: './dist',
  hostname: 'localhost',
  port: 8080,
  fallback: '/200.html',
})

server.start()
